name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          # - linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Create Archive
        run: |
          IMAGE=${{ vars.ORG }}/iwasm:${{ env.TAG }}
          PLATFORM=${{ matrix.platform }}
          PLATFORM_SUFFIX=${PLATFORM//\//-}
          LIB_PATH=lib-${PLATFORM_SUFFIX}
          docker pull --platform $PLATFORM $IMAGE
          docker run --platform $PLATFORM --rm -v ./${LIB_PATH}:/root/lib $IMAGE bash -c "cp -r /app/iwasm/lib/* /root/lib/"
          tar -czf libruntime-${PLATFORM_SUFFIX}.tar.gz lib-${PLATFORM_SUFFIX}/

      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: ${{ inputs.tag || github.ref_name }}
          files: libruntime-*.tar.gz
